--- # Ansible Playbook to configure a set of Raspberry PIs in a consistent and repeatable way
# Software installation and configuration for Raspberry PI boxes acting as Application Servers
- hosts: raspberry_appserver
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/raspberry-config.yml"
    - "{{ src_dir }}/conf/apache2.yml"
  tasks:
    ################################
    ##### Apache2 HTTP Section #####
    ################################
    - name: Install Apache2 
      apt: 
        name: apache2 
        state: present
    - name: Start and enable Apache2
      service: 
        name: apache2 
        state: started
        enabled: yes
    - name: Copy Apache2 utility scripts to remote server
      copy:
        src: "{{ src_dir }}/scripts/apache2"
        dest: "{{ remote_home_dir }}/utilities/apache2/"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"