--- # Ansible Playbook to configure a set of Raspberry PIs in a consistent and repeatable way
- hosts: raspberry
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/raspberry-config.yml"
    - "{{ src_dir }}/conf/apache2.yml"
  tasks:
    ###########################
    ##### Openssl Section #####
    ###########################
    - name: Install Openssl 
      apt: 
        name: openssl 
        state: present
    ################################
    ##### Apache2 HTTP Section #####
    ################################
    - name: Install Apache2 
      apt: 
        name: apache2 
        state: present
    - name: Start and enable Apache2
      service: 
        name: apache2 
        state: started
        enabled: yes
    - name: Copy utility scripts to remote server
      copy:
        src: "{{ src_dir }}/scripts/"
        dest: "{{ remote_home_dir }}/utilities/webservers/"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"