--- # Ansible Playbook to clean up Raspberry PIs in a consistent and repeatable way
# Software un-installation from Raspberry PI boxes acting as Reverse Proxies
- hosts: raspberry_proxy
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/raspberry-config.yml"
    - "{{ src_dir }}/conf/nginx.yml"
  tasks:
    ###################################
    ##### NGINX Uninstall Section #####
    ###################################
    - name: Stop Nginx Services
      service:
        name: nginx
        state: stopped
      ignore_errors: true
    - name: Uninstall Nginx 
      apt: 
        name: nginx 
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: true
    - name: Uninstall Nginx Common
      apt: 
        name: nginx-common
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: true
    - name: Clean NGINX Installation directory {{ nginx_install_dir }}
      file:
        path: "{{ nginx_install_dir }}/"
        state: absent
    #####################################
    ##### Clean Utilities Directory #####
    #####################################
    - name: Clean utilities directory {{ remote_utilities_dir }}
      file:
        path: "{{ remote_utilities_dir }}/"
        state: absent
# Software un-installation from Raspberry PI boxes acting as Application Servers
- hosts: raspberry_appserver
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/raspberry-config.yml"
    - "{{ src_dir }}/conf/apache2.yml"
  tasks:
    ##########################################
    ##### Apache2 HTTP Uninstall Section #####
    ##########################################
    - name: Uninstall Apache2 
      apt: 
        name: apache2 
        state: absent
        purge: yes
        autoremove: yes
    - name: Clean Apache2 Installation directory {{ apache2_install_dir }}
      file:
        path: "{{ apache2_install_dir }}/"
        state: absent
    - name: Clean Apache2 doc directory {{ apache2_doc_dir }}
      file:
        path: "{{ apache2_doc_dir }}/"
        state: absent
    #####################################
    ##### Clean Utilities Directory #####
    #####################################
    - name: Clean utilities directory {{ remote_utilities_dir }}
      file:
        path: "{{ remote_utilities_dir }}/"
        state: absent
    ##############################################
    ##### Clean Windfire application folders #####
    ##############################################
    - name: Clean Windfire folder {{ remote_app_home_dir }}
      file:
        path: "{{ remote_app_home_dir }}/"
        state: absent
    - name: Clean Windfire Restaurants folder {{ remote_windfire_restaurants_dest_dir }}
      file:
        path: "{{ remote_windfire_restaurants_dest_dir }}/"
        state: absent
# Docker un-installation from Raspberry PI boxes
- hosts: raspberry
  remote_user: "{{ user }}"
  become: yes
  vars_files:
    - "{{ src_dir }}/conf/raspberry-config.yml"
  tasks:
    ####################################
    ##### Docker Uninstall Section #####
    ####################################
    - name: Uninstall Docker 
      apt: 
        name: docker-ce
        state: absent
        purge: yes
        autoremove: yes
    - name: Uninstall Docker CLI
      apt: 
        name: docker-ce-cli
        state: absent
        purge: yes
        autoremove: yes
    - name: Remove /var/lib/docker directory
      file:
        path: "/var/lib/docker"
        state: absent