--- # Ansible Playbook to configure a set of Raspberry PIs in a consistent and repeatable way
- hosts: raspberry
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/raspberry-config.yml"
    - "{{ src_dir }}/conf/apache2.yml"
  tasks:
    ##########################################
    ##### Apache2 HTTP Uninstall Section #####
    ##########################################
    - name: Uninstall Apache2 
      apt: 
        name: apache2 
        state: absent
        purge: yes
        autoremove: yes
    - name: Clean Apache2 Installation directory {{ apache2_install_dir }}
      file:
        path: "{{ apache2_install_dir }}/"
        state: absent
    - name: Clean Apache2 doc directory {{ apache2_doc_dir }}
      file:
        path: "{{ apache2_doc_dir }}/"
        state: absent
    #####################################
    ##### Clean Utilities Directory #####
    #####################################
    - name: Clean webservers utilities directory {{ remote_utilities_dir }}
      file:
        path: "{{ remote_utilities_dir }}/"
        state: absent
    ##############################################
    ##### Clean Windfire application folders #####
    ##############################################
    - name: Clean Windfire folder {{ remote_app_home_dir }}
      file:
        path: "{{ remote_app_home_dir }}/"
        state: absent
    - name: Clean Windfire Restaurants folder {{ remote_windfire_restaurants_dest_dir }}
      file:
        path: "{{ remote_windfire_restaurants_dest_dir }}/"
        state: absent