--- # Ansible Playbook to install Docker on Raspberry PIs in a consistent and repeatable way
- name: "Docker playbook"
  hosts: raspberry
  become: yes
  vars:
    docker_install_compose: false
    docker_users:
      - pi
  roles:
    - geerlingguy.docker_arm