--- # Ansible Playbook to uninstall Docker from Raspberry PIs in a consistent and repeatable way
- hosts: raspberry
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  tasks:
    ####################################
    ##### Docker Uninstall Section #####
    ####################################
    - name: Uninstall Docker 
      apt: 
        name: docker-ce
        state: absent
        purge: yes
        autoremove: yes
    - name: Uninstall Docker CLI
      apt: 
        name: docker-ce-cli
        state: absent
        purge: yes
        autoremove: yes
    - name: Remove /var/lib/docker directory
      file:
        path: "/var/lib/docker"
        state: absent